//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialSiteV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string ProfileImage { get; set; }
        public string Favorite1Title { get; set; }
        public string Favorite2Title { get; set; }
        public string Favorite3Title { get; set; }
        public string Favorite1Data { get; set; }
        public string Favorite2Data { get; set; }
        public string Favorite3Data { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
