//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialSiteV4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Favorites = new HashSet<Favorites>();
        }
    
        public int Id { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
    }
}
